# Generated by Django 5.2.1 on 2025-06-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courese_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coureses',
            old_name='desc',
            new_name='description',
        ),
    ]
