# Generated by Django 5.2.1 on 2025-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='joined_projects', to='project_app.user'),
        ),
    ]
